"""Message IDs for Lab 2 server, discovery, and UDP coordination protocols."""

SERVER_GROUP_REGISTER = 1
SERVER_GROUP_REGISTER_RESPONSE = 2
SERVER_CHALLENGE_REQUEST = 3
SERVER_CHALLENGE_RESPONSE = 4
SERVER_SIGNATURE_BUNDLE = 5
SERVER_ROUND_RESULT = 6

ENDPOINT_ANNOUNCEMENT = 200
ENDPOINT_REQUEST = 201
ENDPOINT_GOSSIP = 202

UDP_GROUP_READY = 210
UDP_NONCE_BROADCAST = 211
UDP_SIGNATURE_REPLY = 212
UDP_BATON_PASS = 213
UDP_ACK = 214
UDP_SERVER_HINT = 215

SERVER_MESSAGE_IDS = frozenset(
    {
        SERVER_GROUP_REGISTER,
        SERVER_GROUP_REGISTER_RESPONSE,
        SERVER_CHALLENGE_REQUEST,
        SERVER_CHALLENGE_RESPONSE,
        SERVER_SIGNATURE_BUNDLE,
        SERVER_ROUND_RESULT,
    }
)

CUSTOM_IPV8_MESSAGE_IDS = frozenset(
    {ENDPOINT_ANNOUNCEMENT, ENDPOINT_REQUEST, ENDPOINT_GOSSIP}
)

UDP_MESSAGE_IDS = frozenset(
    {
        UDP_GROUP_READY,
        UDP_NONCE_BROADCAST,
        UDP_SIGNATURE_REPLY,
        UDP_BATON_PASS,
        UDP_ACK,
        UDP_SERVER_HINT,
    }
)

CUSTOM_MESSAGE_IDS = CUSTOM_IPV8_MESSAGE_IDS | UDP_MESSAGE_IDS
